apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: u-services-k8
  name: u-services-k8
spec:
  ports:
  - name: 80-8081
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: u-services-k8
  type: ClusterIP
status:
  loadBalancer: {}

